version: '3.2'

services:
  influxdb:
    build: ./docker/DockerGrafanaInfluxKit/influxdb
    env_file: ./docker/DockerGrafanaInfluxKit/configuration.env
    hostname: influxdb
    networks:
      - network
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    networks:
      - network
    build: ./docker/DockerGrafanaInfluxKit/grafana
    env_file: ./docker/DockerGrafanaInfluxKit/configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  retail-analytics:
    image: retail-analytics:latest
    ports:
      - "5000:5000"
    container_name: retail-analytics
    networks:
      - network
    depends_on:
      - influxdb
      - grafana

volumes:
  grafana_data: {}
  influxdb_data: {}

networks:
  network:
    driver: "bridge"

